apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-wlln
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-wlln
    app.kubernetes.io/part-of: test-app-vvkv
  name: test-component-wlln
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pip-e2e-test
      app.kubernetes.io/instance: test-component-wlln
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pip-e2e-test
        app.kubernetes.io/instance: test-component-wlln
    spec:
      containers:
      - image: quay.io/susdas/test-images:f96341d95d1f46c98d465cdf5c671878
        name: pip-e2e-test
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
