apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-wlln
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-wlln
    app.kubernetes.io/part-of: test-app-vvkv
  name: test-component-wlln
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: test-component-wlln
status:
  loadBalancer: {}
